application: com-jansichermann-baregae
version: 1
runtime: go
api_version: go1

skip_files:
- ^(.*/)?.*\.DS_Store$

handlers:
- url: /static
  static_dir: static/
  expiration: 1m
- url: /.*
  script: app.go
